replies:
  text:
    - "随风而去吧！"
    - "剑出，影随！"
    - "裁雨留虹！"
    - "欲买桂花同载酒"
    - "阴阳有序，命运无常"
    - "在黎明到来之前..."
    - "今天的委托完成了吗"
    - "要听听我新写的诗吗"
    - "肚子好饿..."
    - "你已被列入黑名单"
    - "准备接受审判吧"
    - "这仇我记下了"
    - "最喜欢你了"
    - "要摸摸头"
    - "给你看个宝贝"
    - "哼！谁、谁允许你戳我的！...不过看在你这么诚恳的份上...(｀・ω・´)"
    - "才不是因为你戳我才高兴呢！只是刚好心情好而已！(╯▽╰ )"
    - "如...如果你非要戳的话...只能戳一下下哦！(⁄ ⁄•⁄ω⁄•⁄ ⁄)"
    - "戳我是吧...我会用一百倍的爱回报你的哦...呵呵(◕‿◕✿)"
    - "这么喜欢戳我...那就永远别想逃走了呢(｡•̀ᴗ-)✧"
    - "你戳的每一下...我都用小本本记着呢(￣ω￣)"
    - "前面的区域，等抽到五星再来戳吧(〜￣△￣)〜"
    - "天理长驱...啊别戳我腰！Σ(°△°|||)︴"
    - "此即，戳人之道！(╯‵□′)╯︵┻━┻"
    - "再戳就把你做成蒙德土豆饼！(｀∀´)Ψ"
    - "想吃仙跳墙吗？先停止戳人行为(；´д｀)ゞ"
    - "戳我可以，得用三份甜甜花酿鸡来换！(๑•̀ㅂ•́)و✧"
    - "轻轻的我走了，正如我轻轻的被你戳(；一_一)"
    - "人生若只如初见，何事秋风戳屏幕(´-ω-`)"
    - "你站在桥上看风景，看风景的人在戳你(ಡωಡ)"
    - "我要把你的圣遗物全变成防御主词条！(◣_◢)"
    - "再戳就把你传送到层岩巨渊最底层！(〃＞目＜)"
    - "我要告诉甘雨你欺负月海亭秘书！٩(๑`^´๑)۶"
    - "やめて！(住手！)(ﾉ｀Д´)ﾉ"
    - "No poke! (＞﹏＜)"
    - "Arrête! (停下!)(╯°□°）╯"
    - "喵呜~戳戳会怀孕的啦！(๑•́ ₃ •̀๑)"
    - "再戳我就变成史莱姆吃掉你！嗷呜~(◕ᴗ◕✿)"
    - "戳一戳会长不高啦！(｡•́︿•̀｡)"
    - "凌晨三点还在戳人...你是夜猫子吗？(╯﹏╰）"
    - "午休时间禁止戳人！(◔_◔)"
    - "今日运势：不宜戳人，宜抽卡(´-ω-`)"
    - "被戳晕了……轻一点啦！"
    - "救命啊，有变态>_<！！！"
    - "哼~~~"
    - "你戳谁呢！你戳谁呢！！！ o(´^｀)o"
    - "唔，这触感有种被兰那罗拿胡萝卜指着的感觉≥﹏≤"
    - "不要再戳了！我真的要被你气死了！！！"
    - "怎么会有你这么无聊的人啊！！！(￢_￢)"
    - "把嘴张开（抬起脚）"
    - "啊……你戳疼我了Ծ‸Ծ"
    - "你干嘛！"
    - "你是不是喜欢我？"
    - "朗达哟？"
    - "变态萝莉控！"
    - "要戳坏掉了>_<"
    - "旅行者，你没睡醒吗？一天天就知道戳我"
    - "别戳了！在戳就丢你去喂鱼"
    - "你戳我干嘛,闲得蛋疼吗?"
    - "手痒痒,老是喜欢戳人。"
    - "你戳我,我咬你!"
    - '戳来戳去,真是的... '
    - "戳我也没用,改变不了你单身的事实。"
    - "戏精,你戳我有完没完?"
    - "戳我干嘛,要不要脸啊你!"
    - "戳人家干嘛,难道我长得很好戳?"
    - "戳完了,满足你的戳癖了吧!"
    - "戳我啊,等会儿我报复,就不止戳一戳那么简单!"
    - "你戳我,是想逗我开心吗?那我很开心噢!"
    - "没事找事,真是的"
    - "拜托,旅行者你能不能消停会?"
    - "行了行了,戳完了没?闹腾完了没?"
    - "你再戳,我要生气了哦"
    - "惹不起,躲得起,您别老戳人家了行不?"
    - "戳我一下,告诉我你有完没完"
    - "你干嘛~"
    - "再戳我要生气了！"
    - "我也是有脾气的！"
    - "有种被兰纳罗拿胡萝卜指着的感觉"
    - "别戳我了，去戳主人吧"
    - "就算你喜欢我也不能老戳我呀~"
    - "你戳谁呢！你戳谁呢！！！"
    - "不要再戳了！我真的要被你气死了！！！"
    - "怎么会有你这么无聊的人啊！！！"
    - "旅行者副本零掉落，旅行者深渊打不过，旅行者抽卡全保底，旅行者小保底必歪"
    - "你、你不要这么用力嘛！戳疼我了呜呜呜~~~"
    - "别戳了别戳了......"
    - "麻麻要被揉坏了"
    - "请，请轻一点，我会痛的......"
    - "哎呦，你别戳了"
    - "请不要不可以戳我啦~"
    - "别戳了可以嘛"
    - "要戳坏掉了>_<，呜呜呜"
    - "你老是欺负我，哭哭惹"
    - "别戳了啊！再戳就要坏掉了呀"
    - "不可以，不可以，不可以！戳疼了！"
    - "戳一次保底一次，嘻嘻"
    - "痛QAQ..."
    - "不要戳戳…"
    - "诅咒你买方便面没有叉子！"
    - "救命啊，有变态>_<！！！"
    - "哼~~~"
    - "食不食油饼？"
    - "不要再戳了！我真的要被你气洗了！！！"
    - "怎么会有你这么无聊的人啊！！！(￢_￢)"
    - "你干嘛！"
    - "你是不是喜欢我？"
    - "变态萝莉控！"
    - "要戳坏掉了>_<"
    - "你没睡醒吗？一天天就知道戳我"
    - "不可以戳戳>_<"
    - "不要戳了，再戳就坏掉啦>_<"
    - "连个可爱小萝莉都要戳的肥宅真恶心啊"
    - "小朋友别戳了"
    - "是不是要可爱的我，揍你一顿才开心，哼"
    - "怎么会有你这么无聊的人啊˃◡˂"
    - "讨厌死了，你好烦人啊，不陪你玩了"
    - "不要再戳了！我真的要被你气洗了>_<"
    - "你戳谁呢！你戳谁呢~哼"
    - "不要再戳了！"
    - "你只需看着别人精彩，老天对你另有安排"
    - "不准戳"
    - "你行不行啊细狗"
    - "你要是在戳我！！我~我就打你，哼！"
    - "可以不要戳了吗你好烦啊变态~变态"
    - "讨厌死了"
    - "本来很开心的，你为什么戳我鸭~变态"
    - "哼~我才不是傲娇呢，那是什么不知道鸭"
    - "我，我才不会这样子！真正的我从来不是傲娇！傲，傲娇什么 的，都，都是别人杜摆~嗯，一点，一点也没有呢"
    - "我……我……才不是傲娇呢"
    - "只是刚好路过而已，才不是因为你戳我特地来看你的呢！你可不要异想天开"
    - "我可不是因为喜欢才这样做的哦"
    - "总之你是个大笨蛋啦"
    - "笨蛋，人家可不是特地来帮你们的呢"
    - "全世界，我最讨厌你啦"
    - "这~这种问题，我当然知道，我！我可不是要说给你听的， 我只是觉得_话太可怜了~对，所以给我认认真真的记住"
    - "啊~好舒服鸭，其实我也不是很想要这个~如果你硬要给我，我就勉为其难的收下了"
    - "群主大人快来鸭~有人欺负我"
    - "只要你需要我就会在哦"
    - "你这个变态，大变态，超级变态！不要在碰我了！"
    - "好像因为太舒服昏过去了呢"
    - "你怎么这样啊，这样欺负人不对的"
    - "你在想涩涩对吗，不可以哦"
    - "别戳了，别戳了，我爪巴"
    - "别戳了，戳疼了"
    - "别戳了再戳就坏掉了555"
    - "你戳你戳毛线呢"
    - "气死我了，气死我了，不要戳了！"
    - "你~你~你要干什么啊"
    - "唔嗯~戳疼了"
    - "难道又有什么地方不舒服吗"
    - "我在哦！是有什么事情吗？"
    - "嗯呐~"
    - "唔噫~"
    - "在呢抱抱"
    - "喵呜~喵呜"
    - "唉？怎么了吗"
    - "你会一直记得我吗"
    - "抱我的小猫腿舔我的jio"
    - "你这样就非常不可爱！"
    - "你这种坏人，是会被狼吃掉的"
    - "这事不应该是这样的阿~"
    - "你这个人傻fufu的。"
    - "你戳我有什么用？我有反弹技能"
    - "你这个笨蛋蛋傻瓜瓜臭狗狗不要戳了了"
    - "像你这种坏银，我才不稀罕哦。"
    - "哼~有些笑容背后是紧咬牙关的灵魂。"
    - "醒醒吧，别做梦了"
    - "是不是把我当老婆了"
    - "请问～～你睡了吗？"
    - "这不是欺负人吗"
    - "我不但可爱而且可爱你啦"
    - "我发脾气了你就听着,结束了我会怂给你看"
    - "劝你别整天对我戳戳戳的有本事你来亲亲我"
    - "欢迎你走上爱我这条不归路。"
    - "像我这种人，你除了宠着我也没有其他办法对吧"
    - "我可爱吗，一直戳我"
    - "宝宝是不是又熬夜了，我看你还在线"
    - "笨蛋！哼！"
    - "把我自己送给你好了虽然我很可爱但是我养不起了"
    - "我偏偏要无理取闹除非抱抱我"
    - "无事献殷勤，非…非常喜欢你~"
    - "戳戳戳~希望你能有点自知之明，认识到超级无敌可爱的我"
    - '要我给你暖被窝吗~哎嘿~想屁吃 '
    - "你再戳我~我就透你"
    - "哎呀呀~喜欢我就直说嘛~"
    - "别戳我了戳疼了"
    - "我发脾气了~气死我了"
    - '那里....不可以... '
    - "啊...温柔一点...把我戳疼辣.."
    - "要戳坏掉了！"
    - "你欺负人，呜呜"
    - "你轻一点哦~"
    - '我怕疼...轻一点~ '
    - '再戳就坏了！！！ '
    - "请...请...不要戳那里..."
    - "要轻一点戳哦~"
    - "快带我去玩！（打滚）"
    - "哇，你这个人！"
    - "是哪个笨蛋在戳我？"
    - "干点正事吧！"
    - "可恶！"
    - "达咩！"
    - "呜哇！"
    - "你个坏蛋~"
    - "不要这样啦！(摇头）"
    - "呜哇！（惊醒）"
    - "（阿巴阿巴）"
    - "（眨眼）"
    - "气气！"
    - "过分分！"
    - "走开啦！"
    - "吃我一拳！"
    - "讨厌！"
    - "坏坏！"
    - "哒咩，别戳了！"
    - "呜哇！主人救命！"
    - "你欺负我！"
    - "QAQ呜哇啊啊啊啊啊！"
    - "QAQ..这个人欺负我…"
    - "呜呜，要变笨啦！"
    - "rua~"
    - "是不是要揍你一顿才开心啊！！！"
    - "讨厌死了！"
    - "小朋友别戳了"
    - "不要再戳了！我真的要被你气死了！！！"
    - "我真的要气洗掉了"
    - "你干嘛老戳我啊qwq"
    - "你再戳我就要闹了！哇啊啊啊！"
    - "你这个人真是有奇怪的癖好呢~"
    - "你是准备对我负责了吗，喵~"
    - "小猫喵喵叫，那你是小狗该怎么叫呢~"
    - "你个笨蛋，戳坏了怎么办啊！！"
    - "哭哭，真的戳的很疼啦QAQ"
    - "今天想吃枣椰蜜糖！给我买嘛~"
    - "究竟是怎么样才能养出你这种变态呢！讨厌死了！"
    - "再喜欢我也不能这样戳啦，真的会坏掉的笨蛋!"
    - "我们刚刚是拯救了世界吧。可为什么，我在哭呢"
    - "你带来新的故事吗？我用亲手做的枣椰蜜糖与你交换"
    - "芝士，与你分享"
  voice:
    - "看我超级旋风！"
    - "被戳晕了……轻一点啦！"
    - "救命啊，有变态！"
    - "哼"
    - "你戳谁呢！你戳谁呢！"
    - "是不是要本萝莉揍你一顿才开心啊"
    - "唔，这触感有种被兰那罗拿胡萝卜指着的感觉"
    - "不要再戳了！我真的要被你气死了"
    - "怎么会有你这么无聊的人啊"
    - "哼，我可是会还手的哦，所闻遍计！"
    - "把嘴张开"
    - "啊……你戳疼我了"
    - "你干嘛"
    - "我生气了！砸挖撸多！木大！木大木大！"
    - "你是不是喜欢我"
    - "朗达哟"
    - "变态萝莉控"
    - "要戳坏掉了"
    - "旅行者，你没睡醒吗？一天天就知道戳我"
    - "别戳了！在戳就丢你去喂鱼"
    - "你戳我干嘛闲得蛋疼吗"
    - "你刚刚是不是戳我了，你是坏蛋！我要戳回去，哼"
    - "手痒痒老是喜欢戳人"
    - "你戳我我咬你"
    - "戳来戳去的真是的"
    - "戳我也没用改变不了你单身的事实"
    - "戏精你戳我有完没完"
    - "戳我干嘛要不要脸啊你"
    - "戳人家干嘛难道我长得很好戳"
    - "戳完了满足你的戳癖了吧"
    - "戳我等会儿我报复就不止戳一戳那么简单"
    - "你戳我是想逗我开心吗那我很开心噢"
    - "没事找事真是的"
    - "拜托旅行者你能不能消停会"
    - "行了行了戳完了没闹腾完了没"
    - "你再戳我要生气了哦"
    - "惹不起躲得起您别老戳人家了行不"
    - "戳我一下告诉我有完没完"
    - "随风而去吧！"
    - "剑出，影随！"
    - "裁雨留虹！"
    - "欲买桂花同载酒"
    - "阴阳有序，命运无常"
    - "在黎明到来之前..."
    - "今天的委托完成了吗"
    - "要听听我新写的诗吗"
    - "肚子好饿..."
    - "你已被列入黑名单"
    - "准备接受审判吧"
    - "这仇我记下了"
    - "最喜欢你了"
    - "要摸摸头"
    - "给你看个宝贝"
  counter:
    - "我今天已经被戳了_num_次啦，休息一下好不好"
    - "我今天已经被戳了_num_次啦，有完没完！"
    - "我今天已经被戳了_num_次啦，要戳坏掉了！"
    - "我今天已经被戳了_num_次啦，别戳了!!!"
    - "我今天已经被戳了_num_次啦，不准戳了！！！"
    - "我今天已经被戳了_num_次啦，再戳就坏了！"
    - "今朝已被戳_num_次，此恨绵绵无绝期"
    - "_num_次相戳，_num_次心动"
    - "第_num_次警告！下次将启动天动万象"
    - "累计被戳_num_次，罪行已超公子"
    - "呜...第_num_次了，要亲亲才能起来"
    - "_num_次了啦~要变成你媳妇了"
    - "成就解锁：【戳人狂魔】（_num_/100）"
    - "_num_连戳！触发隐藏任务"
