# 戳一戳配置
chuo: true

probabilities_text: 0.6
probabilities_img: 0.1
probabilities_voice: 0
probabilities_mute: 0.05
probabilities_video: 0.15

settings_master: 主人
settings_mutetime: 1
settings_speakerapi: 纳西妲
settings_emoji_api: https://api.lolimi.cn/API/chaiq/c.php
settings_video_api: https://api.yujn.cn/api/nvda.php?type=video
settings_tts_api: http://1.14.51.4:19191/tts
settings_redis_prefix: "Yz:pokecount:"

# KimiAI设置
moonshot_sk: ""
moonshot_model: moonshot-v1-8k
moonshot_url: https://api.moonshot.cn/v1/chat/completions

# DeepSeekAI配置
deepseek_sk: ""
deepseek_model: deepseek-chat
deepseek_url: https://api.deepseek.com/v1/chat/completions

# QwenAI配置
qwen_api_key: ""
qwen_model: qwen-max
qwen_base_url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
qwen_enable_search: false

# ICQQ表情回应配置
emoji_enable: false
emoji_whiteUserList: []
emoji_blackUserList: []
emoji_whiteGroupList: []
emoji_blackGroupList: []
emoji_faceId: ["66"]
emoji_random: 100
emoji_sleepTime: 100
emoji_all: true


# NTQQ表情回应配置
onebot_emoji_enable: false 
onebot_emoji_whiteUserList: []
onebot_emoji_whiteGroupList: []
onebot_emoji_blackUserList: [] 
onebot_emoji_blackGroupList: []
onebot_emoji_globalRandom: 100
onebot_emoji_sleepTime: 100
onebot_emoji_all: true 
onebot_emoji_fixedEmojiId: 66  


# 系统配置
deviceScaleFactor: 1