- group: '娱乐功能'
  list:
    - icon: 'paimon'
      title: '#模拟人生'
      desc: '对接 AI 的模拟人生'
    - icon: 'paimon'
      title: '戳他@ 1下'
      desc: '戳死你！！'
    - icon: 'paimon'
      title: '今日超能力'
      desc: '随机超能力以及副作用'
    - icon: 'paimon'
      title: '来n份xx涩图'
      desc: '涩图 xx为标签'
- group: 'AI功能'
  list:
    - icon: 'paimon'
      title: '#dp 你好'
      desc: '与 deepseek 对话'
    - icon: 'paimon'
      title: '#qwen 你好'
      desc: '与 通义千问 对话'
    - icon: 'paimon'
      title: '#kimi 你好'
      desc: '与 kimi 对话'
- group: '实用功能'
  list:
    - icon: 'paimon'
      title: '找[@/QQ号]'
      desc: '查看某人的详细QQ信息'
    - icon: 'paimon'
      title: '#清屏'
      desc: '批量撤回，后面可加数字'
    - icon: 'paimon'
      title: '#留言xx @xx或QQ号'
      desc: '给某人留言'
- group: '被动功能'
  list:
    - icon: 'paimon'
      title: '表情回应'
      desc: '请到Guoba配置'
    - icon: 'paimon'
      title: '戳一戳回复'
      desc: '与 通义千问 对话'
    - icon: 'paimon'
      title: '有的兄弟'
      desc: '有的兄弟，有的'
